version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go
    commit-message:
      prefix: deps
    groups:
      go-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: deps
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
