= `dbxcli`: A command line tool for Dropbox users and team admins

This is *BETA* software -- use with caution!

== Features

  * Supports basic file operations like ls, cp, mkdir, mv (via the Files API)
  * Supports search
  * Supports file revisions and file restore
  * Chunked uploads for large files, paginated listing for large directories
  * Supports a growing set of Team operations

== Installation

Download pre-compiled binaries for Mac, Windows and Linux from the https://github.com/dropbox/dbxcli/releases[releases] page.

== Usage

`dbxcli` is largely self documenting. Run `dbxcli -h` for a list of supported commands:

[source, sh]
----
$ dbxcli -h
Use dbxcli to quickly interact with your Dropbox, upload/download files,
manage your team and more. It is easy, scriptable and works on all platforms!

Usage:
  dbxcli [command]

Available Commands:
  cp          Copy files
  du          Display usage information
  get         Download a file
  ls          List files
  mkdir       Create a new directory
  mv          Move files
  put         Upload files
  restore     Restore files
  revs        List file revisions
  rm          Remove files
  search      Search
  team        Team management commands

Flags:
  -h, --help           help for dbxcli
      --token string   Access token
  -v, --verbose        Enable verbose logging

Use "dbxcli [command] --help" for more information about a command.

$ dbxcli team --help
Team management commands

Usage:
  dbxcli team [command]

Available Commands:
  add-member    Add a new member to a team
  list-members  List team members
  remove-member Remove member from a team

Global Flags:
      --token string   Access token
  -v, --verbose        Enable verbose logging

Use "dbxcli team [command] --help" for more information about a command.
----

Note the `--token` option. This is useful for running commands with an alternate token (e.g. when using the Teams API) as well as for debugging.

The `--verbose` option will turn on verbose logging and is useful for debugging.

== We need your help!

`dbxcli` is under active development! As you can see from the https://www.dropbox.com/developers/documentation/http/documentation[API docs], we only support a small number of features today and have only scratched the surface of what's possible. We would love feedback from you, our users, to guide what to build next and how to improve the tool.

So please, file feature requests, report bugs or better yet, send us pull requests! More on contributing below.

== Contributing

 * Step 1: send a https://help.github.com/articles/using-pull-requests/[pull request]
 * Step 2: Profit!
 
**Useful Resources**

* https://godoc.org/github.com/dropbox/dropbox-sdk-go-unofficial[Go SDK documentation]
* https://www.dropbox.com/developers/documentation/http/documentation[API documentation]
