// Copyright © 2026 Dropbox, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/dropbox/dbxcli/v3/cmd"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

const outputDir = "docs/commands"

const destructiveLevelNone = "none"

var stdinStdoutNotes = map[string]string{
	"get":                 "Use `-` as the local target to write downloaded file bytes to stdout; diagnostics go to stderr.",
	"put":                 "Use `-` as the local source to upload from stdin; stdin is spooled to a temporary file before upload.",
	"share-link download": "Use `-` as the target for file shared links to write bytes to stdout; folder shared links require `--recursive` and cannot be written to stdout.",
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	if _, err := os.Stat("go.mod"); err != nil {
		return fmt.Errorf("run from repository root: %w", err)
	}

	root := cmd.RootCmd
	if _, _, err := root.Find([]string{"version"}); err != nil {
		root.AddCommand(cmd.NewVersionCommand("dev"))
	}
	disableAutoGenTag(root)

	if err := os.RemoveAll(outputDir); err != nil {
		return fmt.Errorf("remove %s: %w", outputDir, err)
	}
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", outputDir, err)
	}

	prepender := func(_ string) string {
		return "<!-- Code generated by go run ./tools/gen-docs; DO NOT EDIT. -->\n\n"
	}
	linkHandler := func(name string) string {
		return filepath.Base(name)
	}
	if err := doc.GenMarkdownTreeCustom(root, outputDir, prepender, linkHandler); err != nil {
		return fmt.Errorf("generate command docs: %w", err)
	}
	if err := addCommandMetadata(root); err != nil {
		return err
	}
	return nil
}

func disableAutoGenTag(command *cobra.Command) {
	command.DisableAutoGenTag = true
	for _, child := range command.Commands() {
		disableAutoGenTag(child)
	}
}

func addCommandMetadata(root *cobra.Command) error {
	return walkCommands(root, func(command *cobra.Command) error {
		path := filepath.Join(outputDir, strings.ReplaceAll(command.CommandPath(), " ", "_")+".md")
		contents, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read generated doc %s: %w", path, err)
		}

		updated := insertMetadataSection(contents, commandMetadataSection(command))
		if err := os.WriteFile(path, updated, 0o644); err != nil {
			return fmt.Errorf("write generated doc %s: %w", path, err)
		}
		return nil
	})
}

func walkCommands(command *cobra.Command, fn func(*cobra.Command) error) error {
	if !command.IsAvailableCommand() || command.IsAdditionalHelpTopicCommand() {
		return nil
	}
	if err := fn(command); err != nil {
		return err
	}

	children := append([]*cobra.Command{}, command.Commands()...)
	sort.Slice(children, func(i, j int) bool {
		return children[i].Name() < children[j].Name()
	})
	for _, child := range children {
		if err := walkCommands(child, fn); err != nil {
			return err
		}
	}
	return nil
}

func insertMetadataSection(contents []byte, section []byte) []byte {
	marker := []byte("\n### SEE ALSO\n\n")
	index := bytes.Index(contents, marker)
	if index == -1 {
		return append(append(contents, '\n'), section...)
	}

	result := make([]byte, 0, len(contents)+len(section)+1)
	result = append(result, contents[:index]...)
	result = append(result, '\n')
	result = append(result, section...)
	result = append(result, contents[index:]...)
	return result
}

func commandMetadataSection(command *cobra.Command) []byte {
	manifest := cmd.CommandManifestFor(command)
	var buf bytes.Buffer
	buf.WriteString("### Command metadata\n\n")
	buf.WriteString(fmt.Sprintf("* Structured JSON output: %s\n", yesNo(manifest.SupportsStructuredOutput)))
	buf.WriteString("* JSON help manifest: yes\n")
	buf.WriteString("* Manifest version: `" + manifest.ManifestVersion + "`\n")
	buf.WriteString("* Auth modes: " + markdownValueList(manifest.AuthModes) + "\n")
	buf.WriteString("* Dropbox scopes: " + markdownValueList(manifest.DropboxScopes) + "\n")

	if aliases := sortedAliases(command); len(aliases) > 0 {
		buf.WriteString("* Aliases: ")
		for i, alias := range aliases {
			if i > 0 {
				buf.WriteString(", ")
			}
			buf.WriteString("`" + alias + "`")
		}
		buf.WriteString("\n")
	}

	if len(manifest.Args) > 0 {
		buf.WriteString("* Arguments: ")
		for i, arg := range manifest.Args {
			if i > 0 {
				buf.WriteString(", ")
			}
			requirement := "optional"
			if arg.Required {
				requirement = "required"
			}
			variadic := ""
			if arg.Variadic {
				variadic = ", variadic"
			}
			streamDash := ""
			if arg.StreamDash {
				streamDash = ", `-` stream operand"
			}
			enumValues := ""
			if len(arg.EnumValues) > 0 {
				enumValues = "; values: " + markdownValueList(arg.EnumValues)
			}
			buf.WriteString(fmt.Sprintf("`%s` (%s, %s%s%s%s)", arg.Name, requirement, arg.ValueKind, variadic, streamDash, enumValues))
		}
		buf.WriteString("\n")
	}

	if len(manifest.Flags) > 0 {
		var describedFlags []string
		for _, flag := range manifest.Flags {
			var details []string
			if len(flag.EnumValues) > 0 {
				details = append(details, "values: "+markdownValueList(flag.EnumValues))
			}
			if len(flag.Conflicts) > 0 {
				details = append(details, "conflicts: "+markdownValueList(flag.Conflicts))
			}
			if flag.Sensitive {
				details = append(details, "sensitive")
			}
			if flag.MayPrompt {
				details = append(details, "may prompt")
			}
			if len(details) > 0 {
				describedFlags = append(describedFlags, "`--"+flag.Name+"` ("+strings.Join(details, "; ")+")")
			}
		}
		if len(describedFlags) > 0 {
			buf.WriteString("* Flag metadata: " + strings.Join(describedFlags, ", ") + "\n")
		}
	}

	if note, ok := stdinStdoutNotes[relativeCommandPath(command)]; ok {
		buf.WriteString("* Stdin/stdout behavior: " + note + "\n")
	} else if manifest.StdinStdout.ReadsStdin || manifest.StdinStdout.WritesBinaryStdout {
		buf.WriteString(fmt.Sprintf("* Stdin/stdout behavior: reads_stdin=%t, writes_binary_stdout=%t\n", manifest.StdinStdout.ReadsStdin, manifest.StdinStdout.WritesBinaryStdout))
	}

	if level := manifest.DestructiveLevel; level != destructiveLevelNone {
		buf.WriteString("* Destructive behavior: `" + level + "`\n")
	}
	if len(manifest.ResultStatuses) > 0 {
		buf.WriteString("* Result statuses: " + markdownValueList(manifest.ResultStatuses) + "\n")
	}
	if len(manifest.ResultKinds) > 0 {
		buf.WriteString("* Result kinds: " + markdownValueList(manifest.ResultKinds) + "\n")
	}
	if len(manifest.WarningCodes) > 0 {
		buf.WriteString("* Warning codes: " + markdownValueList(manifest.WarningCodes) + "\n")
	}
	if manifest.SchemaRefs.CommandContract != "" {
		buf.WriteString("* JSON contract: `" + manifest.SchemaRefs.CommandContract + "`\n")
	}
	if manifest.SchemaRefs.CommandSuccessSchema != "" {
		buf.WriteString("* JSON success schema: `" + manifest.SchemaRefs.CommandSuccessSchema + "`\n")
	}

	buf.WriteString("\n")
	return buf.Bytes()
}

func sortedAliases(command *cobra.Command) []string {
	if command == nil || len(command.Aliases) == 0 {
		return nil
	}
	aliases := append([]string{}, command.Aliases...)
	sort.Strings(aliases)
	return aliases
}

func relativeCommandPath(command *cobra.Command) string {
	if command == nil {
		return ""
	}
	path := command.CommandPath()
	if command.Root() != nil {
		rootName := command.Root().Name()
		if path == rootName {
			return path
		}
		return strings.TrimPrefix(path, rootName+" ")
	}
	return path
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

func markdownValueList(values []string) string {
	if len(values) == 0 {
		return "none"
	}
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, "`"+value+"`")
	}
	return strings.Join(quoted, ", ")
}
