name: Continuous Integration

on:
  push:
    branches: [ 'master' ]
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - uses: actions/checkout@v3

      - name: Cache build dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/_go.sum') }}
      
      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -o dbxcli -v
      
      - uses: actions/upload-artifact@v3
        with:
          name: dbxcli
          path: dbxcli
      
